# Generated by Django 3.2.8 on 2021-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('Детектив', 'детектив'), ('Фантастика', 'фантастика'), ('Политика', 'политика'), ('Ужасы', 'ужасы'), ('Роман', 'роман'), ('Психология', 'психология'), ('Наука', 'наука'), ('Детская', 'детская'), ('Юмор', 'юмор')], default='Неизвестен', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
