# Generated by Django 3.2.8 on 2021-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Детектив', 'детектив'), ('Фантастика', 'фантастика'), ('Политика', 'политика'), ('Ужасы', 'ужасы'), ('Роман', 'роман'), ('Психология', 'психология'), ('Наука', 'наука'), ('Детская', 'детская'), ('Юмор', 'юмор')], default='Неизвестен', max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
